"""
Computation of the GXG
===============

GXG (GHG, GVG, GLG) defines the groundwater regime.

Main Components
---------------

Official definitions ground water regime (STOWA, 2008)

* **Hydrologisch jaar -- 1 april t/m 31 maart
* **HG3 -- 3 hoogste 3 grondwaterstanden op basis van 2/mnd in hydrologisch jaar
* **LG3 -- 3 laagste 3 grondwaterstanden op basis van 2/mnd in hydrologisch jaar
* **VG3 -- gemiddelde van 14/3, 28/3 en 14/4

* **GHG gemiddelde HG3 over 8 opeenvolgende jaren
* **GLG gemiddelde LG3 over 8 opeenvolgende jaren
* **GVG gemiddelde VG3 over 8 opeenvolgende jaren

# Hoe ermee om te gaan nu we continudata hebben

Belangrijk concept: **behouden van vergelijkbaarheid** met historische waarden. Daarom kun je de moderne tijdreeks verwerken *zodat je precies dezelfde statistiek* krijgt als vroeger:

2. Voor elk hydrologisch jaar:
   * Sorteer de meetwaarden in dat jaar en neem de **3 hoogste** → HG3(year) = mean(top3).
   * Neem de **3 laagste** → LG3(year) = mean(bot3).
   * Bepaal de **voorjaarsstand**: gemiddelde van 14 en 28 maart en 14 april.

3. Neem **gemiddelde** over de reeks van 8 jaren (bij voorkeur jaren zonder ingrepen).

Reference
---------
https://www.stowa.nl/sites/default/files/assets/PUBLICATIES/Publicaties%202010/STOWA%202010-41.pdf?utm_source=chatgpt.com "GRONDWATERREGIME OP BASIS VAN KARTEERBARE ..."

Example
-------
>>> import mf6lab.regional as reg
>>> reg.setup_model("case01")
>>> reg.run_model("case01")
>>> reg.plot_results("case01")


Origin
------
The code below has been generated by ChatGPT as an exmample.
It muse still be worked out integrated and tested.

TO 2025-10-10
"""

import pandas as pd
import numpy as np

def compute_gxg(ts: pd.Series, hyd_year_start_month=4, min_years=8):
    """
    ts: pd.Series indexed by datetime, values = waterstand (e.g. cm onder maaiveld of mNAP).
    
    hyd_year_start_month: 4  => hydrologisch jaar 1-April .. 31-March
    
    Returns: dict with lists and long-term averages
    """
    # --- Hydrological-year label:
    # --- shift index so year starts at month hyd_year_start_month
    shifted = ts.copy()
    
    # --- ensure Timestamp
    shifted.index = shifted.index.to_period('D').to_timestamp()
    
    # --- create hydrological year label
    def hyd_year(dt):
        y = dt.year
        if dt.month < hyd_year_start_month:
            return y - 1
        return y
    
    years = sorted({hyd_year(idx) for idx in shifted.index})
    
    hg3_list, lg3_list, vfg_list = [], [], []
    
    for y in years:
        start = pd.Timestamp(year=y, month=hyd_year_start_month, day=1)
        end = (start + pd.DateOffset(years=1)) - pd.Timedelta(days=1)
        
        sub = ts[start:end].dropna()
        
        if len(sub) < 3:
            continue
        
        top3_mean = sub.nlargest(3).mean()
        bot3_mean = sub.nsmallest(3).mean()
        
        # --- voorjaarsstand: interpolatie op 1 april if present
        apr1 = pd.Timestamp(year=y, month=4, day=1)
        if apr1 in ts.index:
            v = ts.loc[apr1]
        else:
            # --- linear interpolation to 1-April
            v = ts.reindex(ts.index.union([apr1])).interpolate().loc[apr1]
            
        hg3_list.append(top3_mean)
        lg3_list.append(bot3_mean)
        vfg_list.append(v)
        
    # --- require minimal aantal jaren
    if len(hg3_list) < min_years:
        raise ValueError(f"Not enough years with data: {len(hg3_list)} < {min_years}")
    
    return {
        'HG3_per_year': hg3_list,
        'LG3_per_year': lg3_list,
        'VG3_per_year': vfg_list,
        'GHG': np.mean(hg3_list),
        'GLG': np.mean(lg3_list),
        'GVG': np.mean(vfg_list)
    }
