# -*- coding: utf-8 -*-
"""Run Modflow etc for the current Case.

This script is used to run the Modflow simulation for the current case.
It sets up the simulation, runs it, and checks for successful termination.

It uses the mf_setup function to prepare the simulation environment,
and then it writes the simulation files and runs the simulation using the
Simsim class from the mf_setup module.

The script mf_setup.py is general for mf6lab and does not have to be changed
for each case. It reads mf_adapt, which is specific for the current case.

mf_adapt.py reads settings.put which also is specific for the current case.

If the simulation does not terminate successfully, it raises an exception.
If the simulation is successful, it prints a success message.
This script is typically run from the command line or as part of a larger workflow.
It is assumed that the necessary directories and files are already set up
in the mf_setup function.
It is also assumed that the necessary Python packages are installed and available in the environment.

After running this script, the results of the simulation can be analyzed
using the mf_analyze.py script, which is designed to visualize and interpret the results.

mf_analyze.py is specific for the current case and uses the results
generated by this script to create plots and summaries of the simulation results.

@ TO 2025-07-02
"""

import os
import sys
sys.path.insert(0, "/Users/Theo/GRWMODELS/python/mf6lab/src")

import logging

from mf_setup import mf_setup

logging.info("Running from {}".format(os.getcwd()))

fp_packages, model_dict, use_models, use_packages = mf_setup()

sim = fp_packages.get('Simsim')

sim.write_simulation(silent=False)

success, buff = sim.run_simulation(silent=False)

print('Running success = {}'.format(success))
if not success:
    print(buff)
    logging.critical("Buffer printed because MODFLOW did not terminate normally.")
    raise Exception('MODFLOW did not terminate normally.')
else:
    print("MF6 terminated successfully.")
