/*
 JavaScript tracking client

 @source https://github.com/piwik/piwik/blob/master/js/piwik.js
 @license https://opensource.org/licenses/BSD-3-Clause BSD-3 Clause (also in js/LICENSE.txt)
 @license magnet:?xt=urn:btih:c80d50af7d3db9be66a4d0a86db0286e4fd33292&dn=bsd-3-clause.txt BSD-3-Clause
*/
(function(){function R(a){"@babel/helpers - typeof";return R="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(d){return typeof d}:function(d){return d&&"function"==typeof Symbol&&d.constructor===Symbol&&d!==Symbol.prototype?"symbol":typeof d},R(a)}function M(a){console.error(a)}function id(){if(fc)return vb.exports;fc=1;(function(a,d){(function(f,h){a.exports=h()})(gc,function(){function f(q){return q.charAt(0).toUpperCase()+q.substring(1)}function h(q){return function(){return this[q]}}
function k(q){if(q)for(var p=0;p<y.length;p++)if(void 0!==q[y[p]])this["set"+f(y[p])](q[y[p]])}var n=["isConstructor","isEval","isNative","isToplevel"],l=["columnNumber","lineNumber"],t=["fileName","functionName","source"],y=n.concat(l,t,["args"],["evalOrigin"]);k.prototype={getArgs:function(){return this.args},setArgs:function(q){if("[object Array]"!==Object.prototype.toString.call(q))throw new TypeError("Args must be an Array");this.args=q},getEvalOrigin:function(){return this.evalOrigin},setEvalOrigin:function(q){if(q instanceof
k)this.evalOrigin=q;else if(q instanceof Object)this.evalOrigin=new k(q);else throw new TypeError("Eval Origin must be an Object or StackFrame");},toString:function(){var q=this.getFileName()||"",p=this.getLineNumber()||"",G=this.getColumnNumber()||"",D=this.getFunctionName()||"";return this.getIsEval()?q?"[eval] ("+q+":"+p+":"+G+")":"[eval]:"+p+":"+G:D?D+" ("+q+":"+p+":"+G+")":q+":"+p+":"+G}};k.fromString=function(q){var p=q.indexOf("("),G=q.lastIndexOf(")"),D=q.substring(0,p);p=q.substring(p+1,
G).split(",");q=q.substring(G+1);if(0===q.indexOf("@")){var I=/@(.+?)(?::(\d+))?(?::(\d+))?$/.exec(q,""),K=I[1],S=I[2];I=I[3]}return new k({functionName:D,args:p||void 0,fileName:K,lineNumber:S||void 0,columnNumber:I||void 0})};for(var u=0;u<n.length;u++)k.prototype["get"+f(n[u])]=h(n[u]),k.prototype["set"+f(n[u])]=function(q){return function(p){this[q]=!!p}}(n[u]);for(n=0;n<l.length;n++)k.prototype["get"+f(l[n])]=h(l[n]),k.prototype["set"+f(l[n])]=function(q){return function(p){if(isNaN(parseFloat(p))||
!isFinite(p))throw new TypeError(q+" must be a Number");this[q]=Number(p)}}(l[n]);for(l=0;l<t.length;l++)k.prototype["get"+f(t[l])]=h(t[l]),k.prototype["set"+f(t[l])]=function(q){return function(p){this[q]=String(p)}}(t[l]);return k})})(vb);return vb.exports}function v(a){return"undefined"!==typeof a}function bb(a){return"function"===typeof a}function va(a){return"object"===R(a)}function N(a){return"string"===typeof a||a instanceof String}function Ea(a){return"number"===typeof a||N(a)&&!isNaN(a)&&
""!==a}function fa(a,d){if(a&&a.indexOf)return a.indexOf(d);if(!v(a)||null===a||0===a.length)return-1;for(var f=0;f<a.length;){if(a[f]===d)return f;f++}return-1}function hc(a){if(a)return!v(a.children)&&v(a.childNodes)||v(a.children)?a.children:[]}function wb(a,d){a=String(a);return 0===a.lastIndexOf(d,0)}function Fa(a,d){a=String(a);return-1!==a.indexOf(d,a.length-d.length)}function jd(a,d){var f=r.getAttributeValueFromNode(a,"href");if(!f)return!1;var h=f.split("://");if(2!==h.length)return!1;f=
h[0].toLowerCase();h=h[1];var k=h.indexOf("?");h=-1===k?h:h.slice(0,k);k=[];for(var n=0;n<d.length;n++){var l=d[n];kd.test(l)&&k.push(l)}for(n=0;n<k.length;n++){var t=k[n].split("://");if(2!==t.length)break;l=t[0].toLowerCase();t=t[1];if(f===l&&ic(h,t))return!0}return!1}function ic(a,d){wb(d,"/")||(d="/"+d);wb(a,"/")||(a="/"+a);if("/"===d||"/*"===d||a===d)return!0;d=String(d).toLowerCase();a=String(a).toLowerCase();if(Fa(d,"*"))return(d=d.slice(0,-1))&&"/"!==d&&a!==d?0===a.indexOf(d):!0;Fa(a,"/")||
(a+="/");Fa(d,"/")||(d+="/");return 0===a.indexOf(d)}function xb(a,d){var f="(^| )(piwik[_-]"+d;if(a)for(var h=0;h<a.length;h++)f+="|"+a[h];return new RegExp(f+")( |$)")}function ld(){var a=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance;if(null!==a&&void 0!==a&&a.timing)return a.timing;if(null!==a&&void 0!==a&&a.getEntriesByType)return a.getEntriesByType("navigation")[0]}function O(a,d,f){return 0<=d&&d<=f?"&"+a+"="+d:""}function P(a,d){return Math.round(a[d]-
(a.navigationStart||0))}function md(a){var d="";a.unloadEventStart&&0!==a.unloadEventStart&&(d+=O("t_us",P(a,"unloadEventStart"),65535));a.unloadEventEnd&&0!==a.unloadEventEnd&&(d+=O("t_ue",P(a,"unloadEventEnd"),65535));a.redirectStart&&0!==a.redirectStart&&(d+=O("t_rs",P(a,"redirectStart"),65535));a.redirectEnd&&0!==a.redirectEnd&&(d+=O("t_re",P(a,"redirectEnd"),65535));a.secureConnectionStart&&0!==a.secureConnectionStart&&(d+=O("t_ss",P(a,"secureConnectionStart"),65535));a.fetchStart&&0!==a.fetchStart&&
(d+=O("t_fs",P(a,"fetchStart"),65535));a.domainLookupStart&&0!==a.domainLookupStart&&(d+=O("t_ds",P(a,"domainLookupStart"),65535));a.connectStart&&0!==a.connectStart&&(d+=O("t_cs",P(a,"connectStart"),65535));a.connectEnd&&0!==a.connectEnd&&(d+=O("t_ce",P(a,"connectEnd"),65535));a.requestStart&&0!==a.requestStart&&(d+=O("t_qs",P(a,"requestStart"),65535));a.responseStart&&0!==a.responseStart&&(d+=O("t_as",P(a,"responseStart"),65535));a.responseEnd&&0!==a.responseEnd&&(d+=O("t_ae",P(a,"responseEnd"),
65535));a.domLoading&&0!==a.domLoading&&(d+=O("t_dl",P(a,"domLoading"),65535));a.domInteractive&&0!==a.domInteractive&&(d+=O("t_di",P(a,"domInteractive"),16777215));a.domContentLoadedEventStart&&0!==a.domContentLoadedEventStart&&(d+=O("t_ls",P(a,"domContentLoadedEventStart"),16777215));a.domContentLoadedEventEnd&&0!==a.domContentLoadedEventEnd&&(d+=O("t_le",P(a,"domContentLoadedEventEnd"),16777215));a.domComplete&&0!==a.domComplete&&(d+=O("t_dc",P(a,"domComplete"),16777215));a.loadEventEnd&&0!==a.loadEventEnd&&
(d+=O("t_ee",P(a,"loadEventEnd"),16777215));return d}function nd(a){var d,f="loading",h=void 0;if(null!==(d=navigator.userAgentData)&&void 0!==d&&d.getHighEntropyValues)navigator.userAgentData.getHighEntropyValues("architecture bitness formFactor fullVersionList model platformVersion uaFullVersion wow64".split(" ")).then(function(k){h=k;f="available"})["catch"](function(k){M(k);f="unavailable"})["finally"](function(){a.onResolve()});else f="unavailable";return{getState:function(){return"available"===
f?{state:"available",hints:h}:{state:f}}}}function jc(a){if(!(a instanceof Array))return{isValid:!1,error:"[enableHeartBeatTimer] - 'timers' parameter if specified, has to be array of numbers. Received: '".concat(a,"'")};if(0===a.length)return{isValid:!1,error:"[enableHeartBeatTimer] - 'timers' cannot be empty array"};for(var d=0;d<a.length;d++)if("number"!==typeof a[d])return{isValid:!1,error:"[enableHeartBeatTimer] - 'timers' array has to contain only numeric values. Received: '".concat(a,"'")};
return{isValid:!0}}function od(a){var d=!1,f=!1,h=!0,k=kc,n,l=0,t=function p(){var G=k[l];n=void 0===G?void 0:setTimeout(function(){if(h)a.onPing(wa.PeriodicHeartbeat);l++;p()},1E3*G)},y=function(){f&&(t(),f=!1);h||(h=!0,a.onPing(wa.PeriodicHeartbeat))},u=function(){h=!1;a.onPing(wa.BlurHeartbeat)};return{enable:function(){d=!0;window.addEventListener("focus",y);window.addEventListener("blur",u);document.hasFocus()?t():f=!0},disable:function(){f=d=!1;clearTimeout(n);n=void 0;l=0;window.removeEventListener("focus",
y);window.removeEventListener("blur",u)},setTimings:function(p){var G=jc(p);if(!G.isValid)return M(G.error),this;k=p;return this},isEnabled:function(){return d}}}function Qa(a){var d=/^(?:(?:https?|ftp):)\/*(?:[^@?]+@)?([^:/#]+)/.exec(a);return d?d[1]:a}function lc(a){var d=document.createElement("a");d.href=a;return{href:d.href,hostname:d.hostname,pathname:d.pathname}}function pd(a){var d=function(na,ha){return na<<ha|na>>>32-ha},f=function(na){var ha="",xa;for(xa=7;0<=xa;xa--){var yb=na>>>4*xa&
15;ha+=yb.toString(16)}return ha},h,k=[],n=1732584193,l=4023233417,t=2562383102,y=271733878,u=3285377520,q=[];a=unescape(encodeURIComponent(a));var p=a.length;for(h=0;h<p-3;h+=4){var G=a.charCodeAt(h)<<24|a.charCodeAt(h+1)<<16|a.charCodeAt(h+2)<<8|a.charCodeAt(h+3);q.push(G)}switch(p&3){case 0:h=2147483648;break;case 1:h=a.charCodeAt(p-1)<<24|8388608;break;case 2:h=a.charCodeAt(p-2)<<24|a.charCodeAt(p-1)<<16|32768;break;case 3:h=a.charCodeAt(p-3)<<24|a.charCodeAt(p-2)<<16|a.charCodeAt(p-1)<<8|128}for(q.push(h);14!==
(q.length&15);)q.push(0);q.push(p>>>29);q.push(p<<3&4294967295);for(a=0;a<q.length;a+=16){for(h=0;16>h;h++)k[h]=q[a+h];for(h=16;79>=h;h++)k[h]=d(k[h-3]^k[h-8]^k[h-14]^k[h-16],1);G=n;p=l;var D=t;var I=y;var K=u;for(h=0;19>=h;h++){var S=d(G,5)+(p&D|~p&I)+K+k[h]+1518500249&4294967295;K=I;I=D;D=d(p,30);p=G;G=S}for(h=20;39>=h;h++)S=d(G,5)+(p^D^I)+K+k[h]+1859775393&4294967295,K=I,I=D,D=d(p,30),p=G,G=S;for(h=40;59>=h;h++)S=d(G,5)+(p&D|p&I|D&I)+K+k[h]+2400959708&4294967295,K=I,I=D,D=d(p,30),p=G,G=S;for(h=
60;79>=h;h++)S=d(G,5)+(p^D^I)+K+k[h]+3395469782&4294967295,K=I,I=D,D=d(p,30),p=G,G=S;n=n+G&4294967295;l=l+p&4294967295;t=t+D&4294967295;y=y+I&4294967295;u=u+K&4294967295}S=f(n)+f(l)+f(t)+f(y)+f(u);return S.toLowerCase()}function cb(a,d,f){v(f)||(f="");try{return a[d]||f}catch(h){return f}}function qd(a){if(!a)return!0;var d,f=!0;for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&(f=!1);return f}function Ra(){var a,d;for(a=0;a<arguments.length;a+=1){var f=null;arguments[a]&&arguments[a].slice&&
(f=arguments[a].slice());var h=arguments[a];var k=h.shift();if(N(k)&&0<k.indexOf("::")){var n=k.split("::");var l=n[0];k=n[1];"object"===R(ya[l])&&"function"===typeof ya[l][k]?ya[l][k].apply(ya[l],h):f&&db.push(f)}else for(d=0;d<Q.length;d++)if(N(k)){l=Q[d];if(0<k.indexOf("."))if(n=k.split("."),l&&"object"===R(l[n[0]]))l=l[n[0]],k=n[1];else if(f){db.push(f);break}l[k]?l[k].apply(l,h):M("The method '"+k+'\' was not found in "_paq" variable.  Please have a look at the Piwik tracker documentation');
if("addTracker"===k)break;if("setTrackerUrl"===k||"setSiteId"===k)break}else k.apply(Q[d],h)}}function X(a,d,f,h){if(a.addEventListener)return a.addEventListener(d,f,h),!0;if(a.attachEvent)return a.attachEvent("on"+d,f);a["on"+d]=f}function eb(a,d,f,h){if(a.removeEventListener)return a.removeEventListener(d,f,h),!0;if(a.detachEvent)return a.detachEvent("on"+d,f);a["on"+d]===f&&delete a["on"+d]}function Ga(a){"complete"===B.readyState?a():A.addEventListener?A.addEventListener("load",a):A.attachEvent&&
A.attachEvent("onload",a)}function Sa(a){var d=!1;(d=B.attachEvent?"complete"===B.readyState:"loading"!==B.readyState)?a():(B.addEventListener?X(B,"DOMContentLoaded",function h(){B.removeEventListener("DOMContentLoaded",h,!1);d||(d=!0,a())}):B.attachEvent&&(B.attachEvent("onreadystatechange",function h(){"complete"===B.readyState&&(B.detachEvent("onreadystatechange",h),d||(d=!0,a()))}),B.documentElement.doScroll&&A===A.top&&function k(){if(!d){try{B.documentElement.doScroll("left")}catch(n){setTimeout(k,
0);return}d=!0;a()}}()),X(A,"load",function(){d||(d=!0,a())},!1))}function zb(a,d,f){if(!a)return"";var h="",k,n;for(k in za)Object.prototype.hasOwnProperty.call(za,k)&&(n=za[k]&&"function"===typeof za[k][a])&&(n=za[k][a],(n=n(d||{},f))&&(h+=n));return h}function rd(a,d){var f=B.createElement("script");f.type="text/javascript";f.src=a;f.readyState?f.onreadystatechange=function(){var h=this.readyState;if("loaded"===h||"complete"===h)f.onreadystatechange=null,d()}:f.onload=d;B.getElementsByTagName("head")[0].appendChild(f)}
function sd(){var a="";try{a=A.top.document.referrer}catch(d){if(A.parent)try{a=A.parent.document.referrer}catch(f){a=""}}""===a&&(a=B.referrer);return a}function mc(a){return(a=/^([a-z]+):/.exec(a))?a[1]:null}function nc(a,d){a=String(a);return a.substr(0,a.length-d)}function oc(a,d){a=String(a);if(-1===a.indexOf("?"+d+"=")&&-1===a.indexOf("&"+d+"="))return a;var f=a.indexOf("?");if(-1===f)return a;var h=a.substr(f+1);f=a.substr(0,f);if(h){var k="",n=h.indexOf("#");-1!==n&&(k=h.substr(n+1),h=h.substr(0,
n));n=h.split("&");var l=n.length-1;for(l;0<=l;l--)h=n[l].split("=")[0],h===d&&n.splice(l,1);(h=n.join("&"))&&(f=f+"?"+h);k&&(f+="#"+k)}return f}function pc(a,d){var f=(new RegExp("[\\?&#]"+d+"=([^&#]*)")).exec(a);return f?qc(f[1]):""}function Z(a){return a&&String(a)===a?a.replace(/^\s+|\s+$/g,""):a}function td(a,d,f){a||(a="");d||(d="");if("translate.googleusercontent.com"===a)""===f&&(f=d),d=pc(d,"u"),a=Qa(d);else if("cc.bingj.com"===a||"webcache.googleusercontent.com"===a||"74.6."===a.slice(0,
5))d=B.links[0].href,a=Qa(d);return[a,d,f]}function Ta(a){var d=a.length;"."===a.charAt(--d)&&(a=a.slice(0,d));"*."===a.slice(0,2)&&(a=a.slice(1));-1!==a.indexOf("/")&&(a=a.substr(0,a.indexOf("/")));return a}function rc(a,d){return a&&d?a.contains?a.contains(d):a===d?!0:a.compareDocumentPosition?!!(a.compareDocumentPosition(d)&16):!1:!1}function Ab(a){function d(h,k){if(A.getComputedStyle)return B.defaultView.getComputedStyle(h,null)[k];if(h.currentStyle)return h.currentStyle[k]}function f(h,k,n,
l,t,y,u){var q=h.parentNode,p;a:{for(p=h.parentNode;p;){if(p===B){p=!0;break a}p=p.parentNode}p=!1}if(!p)return!1;if(9===q.nodeType)return!0;if("0"===d(h,"opacity")||"none"===d(h,"display")||"hidden"===d(h,"visibility"))return!1;v(k)&&v(n)&&v(l)&&v(t)&&v(y)&&v(u)||(k=h.offsetTop,t=h.offsetLeft,l=k+h.offsetHeight,n=t+h.offsetWidth,y=h.offsetWidth,u=h.offsetHeight);if(a===h&&(0===u||0===y)&&"hidden"===d(h,"overflow"))return!1;if(q){if("hidden"===d(q,"overflow")||"scroll"===d(q,"overflow"))if(t+1>q.offsetWidth+
q.scrollLeft||t+y-1<q.scrollLeft||k+1>q.offsetHeight+q.scrollTop||k+u-1<q.scrollTop)return!1;h.offsetParent===q&&(t+=q.offsetLeft,k+=q.offsetTop);return f(q,k,n,l,t,y,u)}return!0}return a?f(a):!1}function sc(a,d){if(d)return d;a=E.toAbsoluteUrl(a);var f=String(a);-1!==f.indexOf("?")&&(f=a.indexOf("?"),a=a.slice(0,f));Fa(a,"ppms.php")?a=nc(a,8):Fa(a,".php")&&(f=a.lastIndexOf("/"),a=a.slice(0,f+1));Fa(a,"/js/")&&(a=nc(a,3));return a}function Aa(){var a=/index\.php\?module=Overlay&action=startOverlaySession&idSite=([0-9]+)&period=([^&]+)&date=([^&]+)(&segment=.*)?$/.exec(B.referrer);
if(a){var d=a[2],f=a[3];(a=a[4])?0===a.indexOf("&segment=")&&(a=a.substr(9)):a="";A.name="Piwik_Overlay###"+d+"###"+f+"###"+a}d=A.name.split("###");return 4===d.length&&"Piwik_Overlay"===d[0]}function ud(a,d,f){var h=A.name.split("###"),k=h[1],n=h[2],l=h[3],t=sc(a,d);rd(t+"plugins/Overlay/client/client.js?v=1",function(){Piwik_Overlay_Client.initialize(t,f,k,n,l)})}function Bb(a,d){function f(b){if(!1===Cb||!0===Db){var c=new Date;null!==Eb&&18E5<c-Eb||(c=T("ping=".concat(b),null,"ping"),b=b!==wa.PeriodicHeartbeat,
D(c,J,null,b,b?"beacon":null))}}function h(b,c,e,g,m,w){if(!ia){if(e){var z=new Date;z.setTime(z.getTime()+e)}B.cookie=b+"="+F(c)+(e?";expires="+z.toGMTString():"")+";path="+(g||"/")+(m?";domain="+m:"")+(w?";secure":"")+";SameSite=Lax"}}function k(b){return ia?0:((b=(new RegExp("(^|;)[ ]*"+b+"=([^;]*)")).exec(B.cookie))?qc(b[2]):0)||0}function n(b){b=oc(b,"pk_vid");if(tc){var c=/#.*/;return b.replace(c,"")}return b}function l(b,c){b=String(b).toLowerCase();c=String(c).toLowerCase();if(b===c)return!0;
if("."===c.slice(0,1)){if(b===c.slice(1))return!0;var e=b.length-c.length;if(0<e&&b.slice(e)===c)return!0}return!1}function t(b){var c=document.createElement("a");0!==b.indexOf("//")&&0!==b.indexOf("http")&&(0===b.indexOf("*")&&(b=b.substr(1)),0===b.indexOf(".")&&(b=b.substr(1)),b="http://"+b);c.href=E.toAbsoluteUrl(b);return c.pathname?c.pathname:""}function y(b,c){for(var e=0;e<ja.length;e++){var g=Ta(ja[e]),m=t(ja[e]);if(l(b,g)&&ic(c,m))return!0}return!1}function u(b,c){var e=new Image(1,1);e.onload=
function(){Ha=0;"function"===typeof c&&c()};b=-1!==b.indexOf("send_image=0")?b.replace("&send_image=0","&send_image=1"):b+"&send_image=1";e.src=ka+(0>ka.indexOf("?")?"?":"&")+b}function q(b,c,e){v(e)&&null!==e||(e=!0);try{var g=A.XMLHttpRequest?new A.XMLHttpRequest:A.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;g.open("POST",ka,!0);g.onreadystatechange=function(){4!==this.readyState||200<=this.status&&300>this.status||!e?4===this.readyState&&"function"===typeof c&&c():u(b,c)};g.setRequestHeader("Content-Type",
Fb);g.send(b)}catch(m){e&&u(b,c)}}function p(b){b=(new Date).getTime()+b;if(!Ua||b>Ua)Ua=b}function G(b,c){var e=(new Date).getTime();uc=e;Ia&&e<Ia?(e=Ia-e,setTimeout(b,e),c&&p(e+50),Ia+=50):(!1===Ia&&(Ia=e+800),b())}function D(b,c,e,g,m){if(Gb){var w=vc.getState();if("loading"===w.state){fb.push({type:"single",request:b,delay:c,callback:e,force:g,method:m});return}"available"===w.state&&(b+="&ch=".concat(F(JSON.stringify(w.hints))))}bb(Va)&&(b=Va(b));if(!gb&&b){var z=m||hb,L=!e&&U.sendBeacon&&A.Blob&&
65536>=b.length,C=!0;m=function(){if("beacon"===z&&L){var la=new A.Blob([String(b)],{type:Fb});U.sendBeacon(ka,la)?C=!1:q(b,e)}else"POST"===z||2E3<String(b).length?q(b,e):u(b,e);C&&p(c)};g?m():G(m,C)}}function I(b,c){var e=gb?!1:b&&b.length;if(e){if(Gb){e=vc.getState();if("loading"===e.state){fb.push({type:"bulk",requests:b,delay:c});return}if("available"===e.state)for(var g=0;g<b.length;g++)b[g]+="&ch=".concat(F(JSON.stringify(e.hints)))}if(bb(Va)){e=[];for(g=0;g<b.length;g++){var m=Va(b[g]);m&&
e.push(m)}if(0>=e.length)return;b=e}var w='{"requests":["?'+b.join('","?')+'"]}';G(function(){q(w,null,!1);"beacon"!==hb&&p(c)},!1)}}function K(b){return wc+b+"."+Ba+"."+xc}function S(){if(ia)return"0";if(!v(U.cookieEnabled)){var b=K("_pk_testcookie");h(b,"1",aa,ba,oa);var c="1"===k(b)?"1":"0";h(b,"",-86400,aa,ba,oa);return c}return U.cookieEnabled?"1":"0"}function na(){xc=Hb((ba||Wa)+(aa||"/")).slice(0,4)}function ha(){var b=K("cvar");b=k(b);return b.length&&(b=JSON.parse(b),va(b))?b:{}}function xa(){return Hb((U.userAgent||
"")+(U.platform||"")+JSON.stringify(ca)).slice(0,6)}function yb(b){if(!Ja)return"";b=yc(b,"pk_vid");if(!b)return"";b=String(b);var c=/^[a-zA-Z0-9]+$/;if(16===b.length&&c.test(b))return b;if(32===b.length&&c.test(b)){a:{var e=b.substr(16,32);e=String(e);c=xa();var g=c.length,m=e.substr(-1*g,g);if((e=parseInt(e.substr(0,e.length-g),10))&&m&&m===c&&(c=Math.floor((new Date).getTime()/1E3),0>=Ib||c>=e&&c<=e+Ib)){c=!0;break a}c=!1}if(c)return b.substr(0,16)}return""}function zc(){Ka||(Ka=yb(ib));var b=
Math.round((new Date).getTime()/1E3),c=K("id");if(c=k(c)){var e=c=c.split("."),g=c[0],m,w=[[/g/g,"10"],[/h/g,"11"],[/i/g,"12"],[/j/g,"13"],[/k/g,"14"],[/l/g,"15"],[/m/g,"16"],[/n/g,"17"],[/o/g,"18"],[/p/g,"19"],[/q/g,"1a"],[/r/g,"1b"],[/s/g,"1c"],[/t/g,"1d"],[/u/g,"1e"],[/v/g,"1f"],[/w/g,"20"],[/x/g,"21"],[/y/g,"22"],[/z/g,"23"],[/_/g,"3e"],[/-/g,"3f"]];if(g&&!/^[0-9a-f]{16}$/.test(g)){g=g.toLowerCase().substr(4,16);for(m=0;m<w.length;m+=1)g=g.replace(w[m][0],w[m][1]);g=g.substr(0,16)}e[0]=g;6>c.length&&
(c[1]=b,c[2]=0,c[3]=b,c[4]="",c[5]="");c.unshift("0");Ka.length&&(c[1]=Ka);return c}return c=["1",Ka.length?Ka:"0"===S()?"":Hb((U.userAgent||"")+(U.platform||"")+JSON.stringify(ca)+(new Date).getTime()+Math.random()).slice(0,16),b,0,b,"",""]}function jb(){var b=zc(),c=b[0],e=b[1],g=b[2],m=b[3],w=b[4],z=b[5];v(b[6])||(b[6]="");return{newVisitor:c,uuid:e,createTs:g,visitCount:m,currentVisitTs:w,lastVisitTs:z,lastEcommerceOrderTs:b[6]}}function Jb(b){if(Ba){var c=Math.round((new Date).getTime()/1E3);
v(b)||(b=jb());b=b.uuid+"."+b.createTs+"."+b.visitCount+"."+c+"."+b.lastVisitTs+"."+b.lastEcommerceOrderTs;h(K("id"),b,Kb,aa,ba,oa)}}function Lb(){var b=ia;ia=!1;var c;for(c=0;c<Mb.length;c++){var e=K(Mb[c]);0!==k(e)&&h(e,"",-86400,aa,ba,oa)}ia=b}function Ac(b){if(b&&va(b)){var c=[];for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&c.push(e);var e={};c.sort();var g=c.length,m;for(m=0;m<g;m++)e[c[m]]=b[c[m]];return e}}function T(b,c,e,g){function m(ma,vd){var Bc=JSON.stringify(ma);return 2<Bc.length?
"&"+vd+"="+F(Bc):""}var w=new Date;var z=Math.round(w.getTime()/1E3);var L=V,C=K("ses"),la=K("cvar"),Ca=k(C),Nb=Xa||ib;ia&&Lb();if(gb)return"";C=jb();v(g)||(g="");var H=B.characterSet||B.charset;H&&"utf-8"!==H.toLowerCase()||(H=null);!Ca&&(Ca=La/1E3,!C.lastVisitTs||z-C.lastVisitTs>Ca)&&(C.visitCount++,C.lastVisitTs=C.currentVisitTs);wb(b,"action_name=")&&(Cb=kb,Db=!!C.uuid,Eb=new Date);b+="&idsite="+Ba+"&rec=1&r="+String(Math.random()).slice(2,8)+"&h="+w.getHours()+"&m="+w.getMinutes()+"&s="+w.getSeconds()+
"&url="+F(n(Nb))+(Ob.length?"&urlref="+F(n(Ob)):"")+(Ma&&Ma.length?"&uid="+F(Ma):"")+(kb?"&uia=1":"")+(C.uuid?"&_id="+C.uuid:"")+"&_idts="+C.createTs+"&_idvc="+C.visitCount+(C.lastVisitTs?"&_viewts="+C.lastVisitTs:"")+(String(C.lastEcommerceOrderTs).length?"&_ects="+C.lastEcommerceOrderTs:"")+(H?"&cs="+F(H):"")+"&ts_n="+F(Pb)+"&ts_v="+F(Qb)+(Cc?"":"&rmip=1")+(Dc&&kb?"&dda=1":"");if(!Ec)for(x in ca)Object.prototype.hasOwnProperty.call(ca,x)&&(b+="&"+x+"="+ca[x]);w=[];if(c)for(x in c)Object.prototype.hasOwnProperty.call(c,
x)&&/^dimension\d+$/.test(x)&&(z=x.replace("dimension",""),w.push(parseInt(z,10)),w.push(String(z)),b+="&"+x+"="+c[x],delete c[x]);c&&qd(c)&&(c=null);for(x in da)Object.prototype.hasOwnProperty.call(da,x)&&(z=-1===fa(w,x))&&(z=RegExp("[^\x00-\u007f]"),b=(-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/"))&&null!==da[x].match(z)?b+("&dimension"+x+"="+encodeURIComponent(da[x])):b+("&dimension"+x+"="+da[x]));for(x in pa)Object.prototype.hasOwnProperty.call(pa,x)&&(z=
-1===fa(w,x))&&(b+="&dimension"+encodeURIComponent(x)+"="+encodeURIComponent(pa[x]));c?b+="&data="+F(JSON.stringify(c)):qa&&(b+="&data="+F(JSON.stringify(qa)));c=Ac(ra);w=Ac(lb);b+=m(c,"cvar");b+=m(w,"e_cvar");if(V){b+=m(V,"_cvar");for(x in L)Object.prototype.hasOwnProperty.call(L,x)&&(""===V[x][0]||""===V[x][1])&&delete V[x];Fc&&h(la,JSON.stringify(V),La,aa,ba,oa)}var x=ld();L=null;Rb&&(Sb?L=Sb:x&&x.requestStart&&x.responseEnd&&(L=x.responseEnd-x.requestStart),null!==L&&(b+="&gt_ms="+Math.max(L,
0)));L=x&&x.loadEventEnd&&0!==x.loadEventEnd&&x.fetchStart&&0!==x.fetchStart;Rb&&("log"===e||"ping"===e)&&2>=mb&&!Gc&&L&&(b+=md(x),Gc=!0);nb&&(b+="&pv_id="+nb);C.lastEcommerceOrderTs=v(g)&&String(g).length?g:C.lastEcommerceOrderTs;Jb(C);h(K("ses"),"*",La,aa,ba,oa);b+=zb(e,{tracker:wd,request:b});Tb.length&&(b+="&"+Tb);return b}function xd(b){return va(b)?Object.prototype.hasOwnProperty.call(b,"sku")?Object.prototype.hasOwnProperty.call(b,"customDimensions")&&!va(b.customDimensions)?(M('Invalid "customDimensions" property. Expected Object type, but got: '+
JSON.stringify(b)+"."),!1):!0:(M("Missing required SKU property in ecommerce product: "+JSON.stringify(b)+"."),!1):(M("Invalid ecommerce product: "+JSON.stringify(b)),!1)}function Ya(b,c,e){var g=new Date,m=[];var w=""+sa("");w+="&e_t="+b;if(e){b=e.orderId;var z=e.grandTotal;var L=e.subTotal;var C=e.tax;var la=e.shipping;e=e.discount;if(b){w+="&ec_id="+F(b);var Ca=Math.round(g.getTime()/1E3)}w+="&revenue="+z;Ea(L)&&(w+="&ec_st="+L);Ea(C)&&(w+="&ec_tx="+C);Ea(la)&&(w+="&ec_sh="+la);Ea(e)&&(w+="&ec_dt="+
e)}if(c){for(g=0;g<c.length;g+=1){v(c[g].name)||(c[g].name="");if(!v(c[g].category))c[g].category="";else if(c[g].category instanceof Array)for(e=0;e<c[g].category.length;e+=1)N(c[g].category[e])||(c[g].category[e]="");v(c[g].price)&&0!==String(c[g].price).length||(c[g].price=0);v(c[g].quantity)&&0!==String(c[g].quantity).length||(c[g].quantity=1);v(c[g].brand)&&0!==String(c[g].brand).length||(c[g].brand="");v(c[g].variant)&&0!==String(c[g].variant).length||(c[g].variant="");v(c[g].customDimensions)||
(c[g].customDimensions={});e=m;b=e.push;a:for(z=[c[g].sku,c[g].name,c[g].category,c[g].price,c[g].quantity,c[g].brand,c[g].variant,c[g].customDimensions].slice();0<z.length;){L=z[z.length-1];if(!(C=""===L)&&(C=va(L)))b:{C=void 0;for(C in L)if(Object.hasOwnProperty.call(L,C)){C=!1;break b}C=!0}if(C)z.pop();else break a}b.call(e,z)}w+="&ec_products="+F(JSON.stringify(m))}w=T(w,qa,"ecommerce",Ca);D(w,J)}function Za(b){var c,e=!0;if(b instanceof Array){for(c=0;c<b.length;c+=1)e=e&&xd(b[c]);return e}M("Invalid ecommerce products. Expected value: array of objects. Recieved: "+
JSON.stringify(b)+".")}function yd(b,c){var e;if("object"!==R(b)||null===b)return M("Invalid paymentInformation. Expected object. Recieved: "+JSON.stringify(b)+"."),!1;for(e=0;e<c.length;e+=1){var g=c[e];var m=b[g];if("orderId"===g){if(!v(m)||""===String(m))return M('Invalid paymentInformation. Expected object containing "'+g+'" attribute. Recieved: '+JSON.stringify(b)+"."),!1}else if(!Ea(m))return M('Invalid paymentInformation. Expected object containing [number] "'+g+'" attribute. Recieved: '+JSON.stringify(b)+
"."),!1}return!0}function Hc(b,c){Ea(c)?Za(b)&&Ya("cart-update",b,{grandTotal:c}):M('ecommerceCartUpdate requires [number] "grandTotal" parameter. Recieved: '+JSON.stringify(c)+".")}function Ic(b,c){Za(b)&&yd(c,["orderId","grandTotal"])&&Ya("order",b,c)}function Jc(){var b,c=[];if(Y){for(b in Y)if(Object.prototype.hasOwnProperty.call(Y,b)){var e={sku:Y[b][0],name:Y[b][1],category:Y[b][2],price:Y[b][3],quantity:Y[b][4]};c.push(e)}return c}return[]}function sa(b){b=(b=b||ob)&&b.text?b.text:b;if(!N(b)){var c=
B.getElementsByTagName("title");c&&v(c[0])&&(b=c[0].text)}return"action_name="+F(b)}function pb(b){return ka&&b&&0===String(b).indexOf(ka)}function Ub(b){var c;for(c=b.parentNode;null!==c&&v(c)&&!r.isLinkElement(b);)b=c,c=b.parentNode;return b}function Kc(b){b=Ub(b);if(r.hasNodeAttribute(b,"href")&&v(b.href)){var c=r.getAttributeValueFromNode(b,"href");if(!pb(c)){var e=lc(c),g=e.pathname||t(c);c=e.hostname||Qa(e.href);var m=c.toLowerCase();e=e.href.replace(c,m);if(!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto|tel|data|blob):/i.test(e)){c=
b.className;g=y(m,g);b=r.hasNodeAttribute(b,"download");if(pb(e))c=0;else{m=xb(Lc,"download");var w=xb(Mc,"link"),z=new RegExp("\\.("+ta.join("|")+")([?&#]|$)","i");c=w.test(c)?"link":b||m.test(c)||z.test(e)?"download":g?0:"link"}if(c)return{type:c,href:e}}}}}function qb(b,c,e,g){if(b=E.buildInteractionRequestParams(b,c,e,g))return T("".concat(b,"&").concat(sa()),null,"contentInteraction")}function Vb(b,c){if(!b||!c)return!1;var e,g=E.findTargetNodes(b);for(e=0;e<g.length;e++){var m=g[e];if(rc(m,
c)&&E.shouldIgnoreInteraction(m))return!1}g=E.findTargetNodesNoDefault(b);if(!g||0===g.length)return!0;for(e=0;e<g.length;e++)if(m=g[e],rc(m,c))return!0;return!1}function Nc(b,c,e){if(b){var g=E.findParentContentNode(b);if(g&&Vb(g,b)&&(b=E.buildContentBlock(g)))return!b.target&&e&&(b.target=e),E.buildInteractionRequestParams(c,b.name,b.piece,b.target)}}function Oc(b){if(!ua||!ua.length)return!1;var c,e;for(c=0;c<ua.length;c++)if((e=ua[c])&&e.name===b.name&&e.piece===b.piece&&e.target===b.target)return!0;
return!1}function Pc(b){return function(c){if(b){var e=E.findParentContentNode(b),g;c&&(g=c.target||c.srcElement);g||(g=b);if(Vb(e,g)){"beacon"!==hb&&p(J);r.isLinkElement(b)&&r.hasNodeAttributeWithValue(b,"href")&&r.hasNodeAttributeWithValue(b,E.CONTENT_TARGET_ATTR)&&(c=r.getAttributeValueFromNode(b,"href"),!pb(c)&&b.wasContentTargetAttrReplaced&&r.setAnyAttribute(b,E.CONTENT_TARGET_ATTR,""));c=Kc(b);if(Na&&c&&c.type)return c.type;if(g=E.buildContentBlock(e))if(e=g.name,c=g.piece,g=r.getAttributeValueFromNode(b,
E.CONTENT_TARGET_ATTR)||g.target,e=qb("click",e,c,g))return D("".concat(e,"&").concat(sa()),J),e}}}}function Qc(b){if(b&&b.length){var c,e,g;for(c=0;c<b.length;c++){var m=E.findTargetNodes(b[c]);for(g=0;g<m.length;g++)(e=m[g])&&!e.contentInteractionTrackingSetupDone&&(e.contentInteractionTrackingSetupDone=!0,X(e,"click",Pc(e)))}}}function Rc(b,c){if(!b||!b.length)return[];var e,g;for(e=0;e<b.length;e++)Oc(b[e])?(b.splice(e,1),e--):ua.push(b[e]);if(!b||!b.length)return[];Qc(c);var m=[];for(e=0;e<b.length;e++)(g=
T("".concat(E.buildImpressionRequestParams(b[e].name,b[e].piece,b[e].target),"&").concat(sa()),void 0,"contentImpressions"))&&m.push(g);return m}function $a(b){var c=E.collectContent(b);return Rc(c,b)}function Wb(b){if(!b||!b.length)return[];var c;for(c=0;c<b.length;c++)E.isNodeVisible(b[c])||(b.splice(c,1),c--);return b&&b.length?$a(b):[]}function Sc(b,c,e){b=E.buildImpressionRequestParams(b,c,e);return T("".concat(b,"&").concat(sa()),null,"contentImpression")}function Tc(b,c){if(b){var e=E.findParentContentNode(b);
if(e=E.buildContentBlock(e))return c||(c="Unknown"),qb(c,e.name,e.piece,e.target)}}function Uc(b,c,e,g,m,w){if(0===Z(String(b)).length||0===Z(String(c)).length)return M("Error while logging event: Parameters `category` and `action` must not be empty or filled with whitespaces"),!1;var z=T;b="e_c="+F(b)+"&e_a="+F(c)+(v(e)?"&e_n="+F(e):"")+(v(g)?"&e_v="+F(g):"");m=z(b+"&"+sa(""),m,"event");D(m,J,w)}function Vc(b,c,e,g,m){c=c+"="+F(n(b));(b=Nc(m,"click",b))&&(c+="&"+b);e=T(c,e,"link");D(e,J,g,!0,"beacon")}
function Wc(b,c){return""!==b?b+c.charAt(0).toUpperCase()+c.slice(1):c}function W(b){var c,e,g=["","webkit","ms","moz"];if(!Xc)for(e=0;e<g.length;e++){var m=g[e];if(Object.prototype.hasOwnProperty.call(B,Wc(m,"hidden"))){"prerender"===B[Wc(m,"visibilityState")]&&(c=!0);break}}c?X(B,m+"visibilitychange",function z(){B.removeEventListener(m+"visibilitychange",z,!1);b()}):b()}function Yc(){var b=jb().uuid,c=Math.floor((new Date).getTime()/1E3),e=xa();return b+(String(c)+e)}function Zc(b){if(b&&r.hasNodeAttribute(b,
"href")){var c=r.getAttributeValueFromNode(b,"href");c&&!pb(c)&&(c=$c(c,Yc(),"pk_vid"),null!==c&&r.setAnyAttribute(b,"href",c))}}function Xb(b){if(Ja){var c=Ub(b);if(jd(c,ja)){Zc(c);return}}if((c=Kc(b))&&c.type)Vc(c.href,c.type,void 0,null,b);else if(Ja){b=Ub(b);var e=r.getAttributeValueFromNode(b,"href");if(e)if(e=String(e),0!==e.indexOf("//")&&0!==e.indexOf("http://")&&0!==e.indexOf("https://"))c=!1;else{var g=lc(e);c=g.pathname||t(e);e=(g.hostname||Qa(e)).toLowerCase();c=y(e,c)&&!l(Wa,Ta(e))?!0:
!1}else c=!1;c&&Zc(b)}}function ab(b){return function(c){c=c||A.event;a:{var e=c;var g=e.which,m=R(e.button);g||"undefined"===m||(B.all&&!B.addEventListener?e.button&1?g=1:e.button&2?g=3:e.button&4&&(g=2):0===e.button||"0"===e.button?g=1:e.button&1?g=2:e.button&2&&(g=3));switch(g){case 1:e="left";break a;case 2:e="middle";break a;case 3:e="right";break a}e=void 0}g=c.target||c.srcElement;"click"===c.type?(c=!1,b&&"middle"===e&&(c=!0),g&&!c&&Xb(g)):"mousedown"===c.type?"middle"===e&&g?(rb=e,sb=g):
rb=sb=null:"mouseup"===c.type?(e===rb&&g===sb&&Xb(g),rb=sb=null):"contextmenu"===c.type&&Xb(g)}}function zd(b){function c(g){var m=g.target;if(m.closest)m=m.closest("a");else for(;m&&"A"!==m.tagName;)m=m.parentNode;Yb&&m&&!xb(ad,"ignore").test(m.className)&&ab(b)(g)}function e(){eb(document.body,"click",c,!1);b&&(eb(document.body,"mouseup",c,!1),eb(document.body,"mousedown",c,!1),eb(document.body,"contextmenu",c,!1))}Na||(X(document.body,"click",c,!1),b&&(X(document.body,"mouseup",c,!1),X(document.body,
"mousedown",c,!1),X(document.body,"contextmenu",c,!1)),Na=e)}function bd(b,c,e){function g(){m=!0}if(Oa)return!0;Oa=!0;var m=!1,w,z;Ga(function(){function L(H){setTimeout(function(){Oa&&(m=!1,e.trackVisibleContentImpressions(),L(H))},H)}function C(H){setTimeout(function(){Oa&&(m&&(m=!1,e.trackVisibleContentImpressions()),C(H))},H)}function la(H){if(!H)return!1;var x=H.getBoundingClientRect();if(0>=x.width||0>=x.height)return!1;x=null;A.getComputedStyle?x=B.defaultView.getComputedStyle(H,null):!x&&
H.currentStyle?x=H.currentStyle:x||(x={});return"0"===x.opacity||"none"===x.display||"hidden"===x.visibility?!1:H.parentNode instanceof Element?la(H.parentNode):!0}function Ca(H){var x=[],ma;for(ma=0;ma<H.length;ma+=1)H[ma].isIntersecting&&la(H[ma].target)&&E.isOrWasNodeInViewport(H[ma].target)&&x.push(H[ma].target);H=$a(x);I(H,J)}function Nb(){if(A.IntersectionObserver){Da||(Da=new A.IntersectionObserver(Ca,{threshold:0}));var H=E.findContentNodes();for(z=0;z<H.length;z+=1)H[z].getAttribute(E.CONTENT_WATCHED_ATTR)||
(Da.observe(H[z]),H[z].setAttribute(E.CONTENT_WATCHED_ATTR,"1"));return!0}return!1}(b||c&&0<c)&&Nb();if(b){w=["scroll","resize"];for(z=0;z<w.length;z++)B.addEventListener?B.addEventListener(w[z],g):A.attachEvent("on"+w[z],g);C(100)}c&&0<c&&(c=parseInt(c,10),L(c))})}function cd(b,c,e,g){if(Zb){var m=String(b).substring(0,16E3);W(function(){var w=c+":"+e;g&&(w+=":"+g);var z=JSON.stringify({category:"JavaScript Errors",action:w,message:m});dd&&-1!==fa($b,z)||($b.push(z),Uc("JavaScript Errors",w,m))})}}
var tb={},wd=this,ac=td(B.domain,A.location.href,sd()),Wa=Ta(ac[0]),ib=ac[1],Ob=ac[2],Zb=!1,hb="beacon",Cc=!0,Dc=!1,Gb=!1,Fb="application/x-www-form-urlencoded; charset=UTF-8",ka=a||"",bc="",Tb="",Ba=d||"",kb=!1,Ec=!1,Cb=null,Db=null,Ma="",Ka="",cc=10,Xa,ob="",ta="7z aac apk arc arj asf asx avi azw3 bin csv deb dmg doc docx epub exe flv gif gz gzip hqx ibooks jar jpg jpeg js mobi mp2 mp3 mp4 mpg mpeg mov movie msi msp odb odf odg ods odt ogg ogv pdf phps png ppt pptx qt qtm ra ram rar rpm sea sit tar tbz tbz2 bz bz2 tgz torrent txt wav wma wmv wpd xls xlsx xml z zip".split(" "),
ja=[Wa],ad=[],Lc=[],Mc=[],J=500,Eb=null,ed=!1,tc,qa,wc="_pk_",Ib=180,ba,aa,oa=!1,ia=!1,fd=!0,gb,Xc,Kb=339552E5,La=18E5,Rb=!0,Sb=0,Fc=!1,V=!1,Va,ra={},lb={},da={},pa={},dc=200,Y={},ca={},ua=[],Oa=!1,Da,Ia=!1,Na=!1,Yb=!1,Ja=!1,$c=function(b,c,e){b=oc(b,e);b=String(b);c||(c="");var g=B.createElement("a");g.href=b;b=g.search.split("&");b.push(F(e)+"="+F(c));""===b[0]&&b.shift();g.search=b.join("&");return g.href},yc=pc,uc=null,rb,sb,Hb=pd,xc,nb,mb=0,dd=!1,$b=[],Mb=["id","ses","cvar"],Pb="jstc",Qb="2.23.1",
vc=nd({onResolve:function(){for(var b=0;b<fb.length;b++){var c=fb[b];if("single"===c.type)D(c.request,c.delay,c.callback,c.force,c.method);else if("bulk"===c.type)I(c.requests,c.delay);else throw Error("[processQueue] unprocessable request type: ".concat(c));}}});try{ob=B.title}catch(b){ob=""}var Pa=od({onPing:f}),fb=[];this.setCustomVariableMaximumLength=function(b){dc=b};(function(){var b={pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",
dir:"application/x-director",fla:"application/x-shockwave-flash",java:"application/x-java-vm",gears:"application/x-googlegears",ag:"application/x-silverlight"};if(!/MSIE/.test(U.userAgent)){if(U.mimeTypes&&U.mimeTypes.length)for(e in b)if(Object.prototype.hasOwnProperty.call(b,e)){var c=U.mimeTypes[b[e]];ca[e]=c&&c.enabledPlugin?"1":"0"}bb(navigator.javaEnabled)&&U.javaEnabled()&&(ca.java="1");bb(A.GearsFactory)&&(ca.gears="1");ca.cookie=S()}var e=parseInt(gd.width,10);c=parseInt(gd.height,10);ca.res=
parseInt(e,10)+"x"+parseInt(c,10)})();na();zb("run",null,function(b,c){var e=null;if(N(b)&&!v(tb[b])&&c){if(va(c))e=c;else if(N(c))try{eval("hookObj ="+c)}catch(g){}tb[b]=e}return e});this.hook=tb;this.getHook=function(b){return tb[b]};this.getQuery=function(){return r};this.getContent=function(){return E};this.buildContentImpressionRequest=Sc;this.buildContentInteractionRequest=qb;this.buildContentInteractionRequestNode=Tc;this.getContentImpressionsRequestsFromNodes=$a;this.getCurrentlyVisibleContentImpressionsRequestsIfNotTrackedYet=
Wb;this.trackCallbackOnLoad=Ga;this.trackCallbackOnReady=Sa;this.buildContentImpressionsRequests=Rc;this.wasContentImpressionAlreadyTracked=Oc;this.appendContentInteractionToRequestIfPossible=Nc;this.setupInteractionsTracking=Qc;this.trackContentImpressionClickInteraction=Pc;this.internalIsNodeVisible=Ab;this.isNodeAuthorizedToTriggerInteraction=Vb;this.getDomains=function(){return ja};this.getConfigIdPageView=function(){return nb};this.getConfigDownloadExtensions=function(){return ta};this.enableTrackOnlyVisibleContent=
function(b,c){return bd(b,c,this)};this.clearTrackedContentImpressions=function(){ua=[]};this.getTrackedContentImpressions=function(){return ua};this.clearEnableTrackOnlyVisibleContent=function(){Oa=!1;Da&&Da.disconnect();Da=null};this.disableLinkTracking=function(){"function"===typeof Na&&Na();Yb=Na=!1};this.getConfigVisitorCookieTimeout=function(){return Kb};this.removeAllAsyncTrackersButFirst=function(){Q=[Q[0]]};this.ping=function(){var b=T("ping=6",null,"ping");D(b,J)};this.getVisitorId=function(){return jb().uuid};
this.getVisitorInfo=function(){return zc()};this.setTrackerUrl=function(b){ka=b};this.getTrackerUrl=function(){return ka};this.getPiwikUrl=function(){return sc(this.getTrackerUrl(),bc)};this.addTracker=function(b,c){if(!c)throw Error("A siteId must be given to add a new tracker");v(b)&&null!==b||(b=this.getTrackerUrl());var e=new Bb(b,c);Q.push(e);return e};this.getSiteId=function(){return Ba};this.setSiteId=function(b){Ba=b;Jb();if(fd){var c=this.getTrackerUrl(),e=B.createElement("script");e.setAttribute("id",
"ppas_container_configuration");e.setAttribute("data-appid",b);b=e.setAttribute;var g=B.createElement("a");g.href=c;b.call(e,"data-host",g.host);B.getElementsByTagName("head")[0].appendChild(e)}};this.setVisitorIdCookie=function(){Jb()};this.resetUserId=function(){Ma=""};this.setUserIsAnonymous=function(b){kb=b};this.setSessionIdStrictPrivacyMode=function(b){Ec=b};this.setTimingDataSamplingOnPageLoad=function(b){!0===b&&(b=1);!1===b&&(b=0);b=parseInt(b,10);0>b?b=0:100<b&&(b=100);cc=b};this.getTimingDataSamplingOnPageLoad=
function(){return cc};this.setUserId=function(b){v(b)&&b.length&&(Ma=b)};this.getUserId=function(){return Ma};this.setCustomData=function(b,c){va(b)?qa=b:(qa||(qa={}),qa[b]=c)};this.getCustomData=function(){return qa};this.setCustomRequestProcessing=function(b){Va=b};this.appendToTrackingUrl=function(b){Tb=b};this.getRequest=function(b){return T(b)};this.addPlugin=function(b,c){za[b]=c};this.setCustomDimension=function(b,c){b=parseInt(b,10);0<b&&(Object.prototype.hasOwnProperty.call(pa,b)?console.warn("Custom dimension "+
b+' was already set by "setCustomDimensionValue" method. Value set by "setCustomDimension" will be ignored.'):(v(c)||(c=""),N(c)||(c=String(c)),da[b]=c))};this.getCustomDimension=function(b){b=parseInt(b,10);if(0<b&&Object.prototype.hasOwnProperty.call(da,b))return da[b]};this.deleteCustomDimension=function(b){b=parseInt(b,10);0<b&&(delete da[b],delete pa[b])};this.setCustomDimensionValue=function(b,c){b=parseInt(b,10);0<b&&(v(c)||(c=""),N(c)||(c=String(c)),pa[b]=c,delete da[b])};this.getCustomDimensionValue=
function(b){b=parseInt(b,10);if(0<b&&Object.prototype.hasOwnProperty.call(pa,b))return pa[b]};this.setCustomVariable=function(b,c,e,g){v(g)||(g="visit");v(c)&&(v(e)||(e=""),0<b&&(c=N(c)?c:String(c),e=N(e)?e:String(e),c=[c.slice(0,dc),e.slice(0,dc)],"visit"===g||2===g?(!1===V&&(V=ha()),V[b]=c):"page"===g||3===g?ra[b]=c:"event"===g&&(lb[b]=c)))};this.getCustomVariable=function(b,c){v(c)||(c="visit");if("page"===c||3===c)var e=ra[b];else if("event"===c)e=lb[b];else if("visit"===c||2===c)!1===V&&(V=ha()),
e=V[b];return!v(e)||e&&""===e[0]?!1:e};this.deleteCustomVariable=function(b,c){this.getCustomVariable(b,c)&&this.setCustomVariable(b,"","",c)};this.deleteCustomVariables=function(b){if("page"===b||3===b)ra={};else if("event"===b)lb={};else if("visit"===b||2===b)V={}};this.storeCustomVariablesInCookie=function(){Fc=!0};this.setLinkTrackingTimer=function(b){J=b};this.getLinkTrackingTimer=function(){return J};this.setDownloadExtensions=function(b){N(b)&&(b=b.split("|"));ta=b};this.addDownloadExtensions=
function(b){var c;N(b)&&(b=b.split("|"));for(c=0;c<b.length;c++)ta.push(b[c])};this.removeDownloadExtensions=function(b){var c,e=[];N(b)&&(b=b.split("|"));for(c=0;c<ta.length;c++)-1===fa(b,ta[c])&&e.push(ta[c]);ta=e};this.setDomains=function(b){ja=N(b)?[b]:b;b=!1;for(var c=0;c<ja.length;c++){var e=String(ja[c]);if(l(Wa,Ta(e))){b=!0;break}if((e=t(e))&&"/"!==e&&"/*"!==e){b=!0;break}}b||ja.push(Wa)};this.enableCrossDomainLinking=function(){Ja=!0};this.disableCrossDomainLinking=function(){Ja=!1};this.isCrossDomainLinkingEnabled=
function(){return Ja};this.customCrossDomainLinkDecorator=function(b){$c=b};this.customCrossDomainLinkVisitorIdGetter=function(b){yc=b};this.setCrossDomainLinkingTimeout=function(b){Ib=b};this.getCrossDomainLinkingUrlParameter=function(){return F("pk_vid")+"="+F(Yc())};this.setIgnoreClasses=function(b){ad=N(b)?[b]:b};this.setRequestMethod=function(b){hb=b||"beacon"};this.setRequestContentType=function(b){Fb=b||"application/x-www-form-urlencoded; charset=UTF-8"};this.setReferrerUrl=function(b){Ob=
b};this.setCustomUrl=function(b){var c=ib;if(mc(b))Xa=b;else if("/"===b.slice(0,1))Xa=mc(c)+"://"+Qa(c)+b;else{c=n(c);var e=c.indexOf("?");0<=e&&(c=c.slice(0,e));e=c.lastIndexOf("/");e!==c.length-1&&(c=c.slice(0,e+1));Xa=c+b}};this.getCurrentUrl=function(){return Xa||ib};this.setDocumentTitle=function(b){ob=b};this.setAPIUrl=function(b){bc=b};this.setDownloadClasses=function(b){Lc=N(b)?[b]:b};this.setLinkClasses=function(b){Mc=N(b)?[b]:b};this.discardHashTag=function(b){tc=b};this.setCookieNamePrefix=
function(b){wc=b;V=ha()};this.setCookieDomain=function(b){ba=Ta(b);na()};this.getCookieDomain=function(){return ba};this.hasCookies=function(){return"1"===S()};this.setSessionCookie=function(b,c,e){if(!b)throw Error("Missing cookie name");v(e)||(e=La);Mb.push(b);h(K(b),c,e,aa,ba,oa)};this.getCookie=function(b){b=k(K(b));return 0===b?null:b};this.setCookiePath=function(b){aa=b;na()};this.getCookiePath=function(){return aa};this.setVisitorCookieTimeout=function(b){Kb=1E3*b};this.setSessionCookieTimeout=
function(b){La=1E3*b};this.getSessionCookieTimeout=function(){return La};this.setReferralCookieTimeout=function(b){};this.setSecureCookie=function(b){oa=b};this.disableCookies=function(){ia=!0;Ba&&Lb()};this.enableCookies=function(){ia=!1};this.deleteCookies=function(){Lb()};this.setSiteInspectorSetup=function(b){fd=b};this.setDoNotTrack=function(b){var c=U.doNotTrack||U.msDoNotTrack;(gb=b&&("yes"===c||"1"===c))&&this.disableCookies()};this.addListener=function(b,c){var e=c;"undefined"===R(e)&&(e=
!0);X(b,"click",ab(e),!1);e&&(X(b,"mouseup",ab(e),!1),X(b,"mousedown",ab(e),!1),X(b,"contextmenu",ab(e),!1))};this.enableLinkTracking=function(b){this.disableLinkTracking();"undefined"===typeof b&&(b=!0);Yb=!0;W(function(){Sa(function(){zd(b)})})};this.enableJSErrorTracking=function(b){v(b)||(b=!0);if(!Zb){Zb=!0;dd=b;var c=A.onerror;A.onerror=function(e,g,m,w,z){cd(e,g,m,w);return c?c(e,g,m,w,z):!1}}};this.disablePerformanceTracking=function(){Rb=!1};this.setGenerationTimeMs=function(b){Sb=parseInt(b,
10)};this.enableHeartBeatTimer=function(b){if(b){var c=jc(b);if(!c.isValid){M(c.error);return}}else b=kc;Pa.setTimings(b);ed=!0;null!==uc&&Pa.enable()};this.disableHeartBeatTimer=function(){Pa.disable()};this.killFrame=function(){A.location!==A.top.location&&(A.top.location=A.location)};this.redirectFile=function(b){"file:"===A.location.protocol&&(A.location=b)};this.setCountPreRendered=function(b){Xc=b};this.trackGoal=function(b,c,e){W(function(){var g=T("idgoal="+b+(c?"&revenue="+c:"")+"&"+sa(""),
e,"goal");D(g,J)})};this.trackLink=function(b,c,e,g){W(function(){Vc(b,c,e,g)})};this.getNumTrackedPageViews=function(){return mb};this.trackHeartBeat=function(b){var c=!B.hasFocus||B.hasFocus();Pa.isEnabled()&&c&&(!1===Cb||!0===Db)&&(c=wa.PeriodicHeartbeat,b.lastHeartbeat&&(c=wa.LastHeartbeat),b.blurHeartbeat&&(c=wa.BlurHeartbeat),f(c))};this.trackPageView=function(b,c,e){ua=[];$b=[];Aa()?W(function(){ud(ka,bc,Ba)}):(W(function(){mb++;var g="",m;for(m=0;6>m;m++)g+="abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ".charAt(Math.floor(62*
Math.random()));nb=g;g=T(sa(b),c,"log");D(g,J,e);ed&&!Pa.isEnabled()&&Pa.enable()}),1>=mb&&cc>=Math.floor(100*Math.random()+1)&&Ga(function(){setTimeout(function(){var g=T("ping=5",null,"ping");D(g,J)},0)}))};this.trackAllContentImpressions=function(){Aa()||W(function(){Sa(function(){var b=E.findContentNodes();b=$a(b);I(b,J)})})};this.trackVisibleContentImpressions=function(b,c){Aa()||(v(b)||(b=!0),v(c)||(c=750),bd(b,c,this),Da||W(function(){Ga(function(){var e=E.findContentNodes();e=Wb(e);I(e,J)})}))};
this.trackContentImpression=function(b,c,e){Aa()||(b=Z(b),c=Z(c),e=Z(e),b&&(c=c||"Unknown",W(function(){var g=Sc(b,c,e);D(g,J)})))};this.trackContentImpressionsWithinNode=function(b){!Aa()&&b&&W(function(){Oa?Ga(function(){var c=E.findContentNodesWithinNode(b);c=Wb(c);I(c,J)}):Sa(function(){var c=E.findContentNodesWithinNode(b);c=$a(c);I(c,J)})})};this.trackContentInteraction=function(b,c,e,g){Aa()||(b=Z(b),c=Z(c),e=Z(e),g=Z(g),b&&c&&(e=e||"Unknown",W(function(){var m=qb(b,c,e,g);D(m,J)})))};this.trackContentInteractionNode=
function(b,c){!Aa()&&b&&W(function(){var e=Tc(b,c);D(e,J)})};this.logAllContentBlocksOnPage=function(){var b=E.findContentNodes();b=E.collectContent(b);console.log(b)};this.trackEvent=function(b,c,e,g,m,w){W(function(){Uc(b,c,e,g,m,w)})};this.trackSiteSearch=function(b,c,e,g){W(function(){var m=T("search="+F(b)+(c?"&search_cats="+F(JSON.stringify(N(c)?[c]:c)):"")+(v(e)?"&search_count="+e:""),g,"sitesearch");D(m,J)})};this.setEcommerceView=function(b,c,e,g){v(e)&&e.length?e instanceof Array&&(e=JSON.stringify(e)):
e="";ra[5]=["_pkc",e];v(g)&&String(g).length&&(ra[2]=["_pkp",g]);if(v(b)&&b.length||v(c)&&c.length)v(b)&&b.length&&(ra[3]=["_pks",b]),v(c)&&c.length||(c=""),ra[4]=["_pkn",c]};this.getEcommerceItems=function(){return JSON.parse(JSON.stringify(Y))};this.addEcommerceItem=function(b,c,e,g,m){b.length&&(Y[b]=[b,c,e,g,m])};this.removeEcommerceItem=function(b){b.length&&delete Y[b]};this.clearEcommerceCart=function(){Y={}};this.trackEcommerceOrder=function(b,c,e,g,m,w){String(b).length&&v(c)&&(Ic(Jc(),{orderId:b,
grandTotal:c,subTotal:e,tax:g,shipping:m,discount:w}),Y={})};this.trackEcommerceCartUpdate=function(b){Hc(Jc(),b)};this.ecommerceProductDetailView=function(b){Za(b)&&Ya("product-detail-view",b)};this.ecommerceAddToCart=function(b){Za(b)&&Ya("add-to-cart",b)};this.ecommerceRemoveFromCart=function(b){Za(b)&&Ya("remove-from-cart",b)};this.ecommerceCartUpdate=Hc;this.ecommerceOrder=Ic;this.trackError=function(b){if(b){try{var c=Ad.parse(b);var e=c[0]}catch(g){}cd(cb(b,"message"),cb(e,"fileName"),cb(e,
"lineNumber"),cb(e,"columnNumber"))}};this.trackRequest=function(b,c,e,g){W(function(){var m=T(b,c,g);D(m,J,e)})};this.deanonymizeUser=function(){this.setUserIsAnonymous(0);var b=T("ping=4",null,"ping");D(b,J)};this.getTrackingSource=function(){return[Pb,Qb]};this.setTrackingSource=function(b,c){Pb=String(b);void 0!==c&&(Qb=String(c))};this.setIpTracking=function(b){Cc=b};this.setDeviceDataAnonymization=function(b){"boolean"!==typeof b?M("setDeviceDataAnonymization: The value for device data anonymization must be a boolean"):
Dc=b};this.setEnableClientHints=function(b){"boolean"!==typeof b?M("[setEnableClientHints]: The value for enabling client hints must be a boolean"):Gb=b};ya.trigger("TrackerSetup",[this])}function Bd(){return{push:Ra}}function Cd(a,d){var f={},h,k;for(h=0;h<d.length;h++){var n=d[h];f[n]=1;for(k=0;k<a.length;k++)if(a[k]&&a[k][0]){var l=a[k][0];n===l&&(Ra(a[k]),delete a[k],1<f[l]&&"addTracker"!==l&&"enableLinkTracking"!==l&&M("The method "+l+' is registered more than once in "_paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation'),
f[l]++)}}Ra(["setVisitorIdCookie"]);return a}function hd(a,d){var f=new Bb(a,d);Q.push(f);window._paq=Cd(window._paq,Dd);for(Ha=0;Ha<window._paq.length;Ha++)window._paq[Ha]&&Ra(window._paq[Ha]);if("number"===typeof window._paq.length){var h=new Bd,k=new Date;window._paq=h;var n=setInterval(function(){6E4<new Date-k?clearInterval(n):window._paq!==h&&(M("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/."),
clearInterval(n))},1E3)}else M("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/.");return f}function Ed(a,d,f,h){function k(l){try{if(window["piwik_"+l])return window["piwik_"+l]}catch(t){}}var n=window.Piwik.getTracker(f,d);n.setDocumentTitle(a);n.setCustomData(h);(a=k("tracker_pause"))&&
n.setLinkTrackingTimer(a);(a=k("download_extensions"))&&n.setDownloadExtensions(a);(a=k("hosts_alias"))&&n.setDomains(a);(a=k("ignore_classes"))&&n.setIgnoreClasses(a);n.setTimingDataSamplingOnPageLoad(0);n.trackPageView();k("install_tracker")&&(window.piwik_track=function(l,t,y,u){n.setSiteId(t);n.setTrackerUrl(y);n.trackLink(l,u)},n.enableLinkTracking())}var gc="undefined"!==typeof globalThis?globalThis:"undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?
self:{},ub={exports:{}},vb={exports:{}},fc;(function(a,d){(function(f,h){a.exports=h(id())})(gc,function(f){var h=/(^|@)\S+:\d+/,k=/^\s*at .*(\S+:\d+|\(native\))/m,n=/^(eval@)?(\[native code])?$/;return{parse:function(l){if("undefined"!==typeof l.stacktrace||"undefined"!==typeof l["opera#sourceloc"])return this.parseOpera(l);if(l.stack&&l.stack.match(k))return this.parseV8OrIE(l);if(l.stack)return this.parseFFOrSafari(l);throw Error("Cannot parse given Error object");},extractLocation:function(l){if(-1===
l.indexOf(":"))return[l];l=/(.+?)(?::(\d+))?(?::(\d+))?$/.exec(l.replace(/[()]/g,""));return[l[1],l[2]||void 0,l[3]||void 0]},parseV8OrIE:function(l){return l.stack.split("\n").filter(function(t){return!!t.match(k)},this).map(function(t){-1<t.indexOf("(eval ")&&(t=t.replace(/eval code/g,"eval").replace(/(\(eval at [^()]*)|(,.*$)/g,""));var y=t.replace(/^\s+/,"").replace(/\(eval code/g,"(").replace(/^.*?\s+/,""),u=y.match(/ (\(.+\)$)/);y=u?y.replace(u[0],""):y;var q=this.extractLocation(u?u[1]:y);
y=u&&y||void 0;u=-1<["eval","<anonymous>"].indexOf(q[0])?void 0:q[0];return new f({functionName:y,fileName:u,lineNumber:q[1],columnNumber:q[2],source:t})},this)},parseFFOrSafari:function(l){return l.stack.split("\n").filter(function(t){return!t.match(n)},this).map(function(t){-1<t.indexOf(" > eval")&&(t=t.replace(/ line (\d+)(?: > eval line \d+)* > eval:\d+:\d+/g,":$1"));if(-1===t.indexOf("@")&&-1===t.indexOf(":"))return new f({functionName:t});var y=/((.*".+"[^@]*)?[^@]*)(?:@)/,u=t.match(y);u=u&&
u[1]?u[1]:void 0;y=this.extractLocation(t.replace(y,""));return new f({functionName:u,fileName:y[0],lineNumber:y[1],columnNumber:y[2],source:t})},this)},parseOpera:function(l){return!l.stacktrace||-1<l.message.indexOf("\n")&&l.message.split("\n").length>l.stacktrace.split("\n").length?this.parseOpera9(l):l.stack?this.parseOpera11(l):this.parseOpera10(l)},parseOpera9:function(l){var t=/Line (\d+).*script (?:in )?(\S+)/i;l=l.message.split("\n");for(var y=[],u=2,q=l.length;u<q;u+=2){var p=t.exec(l[u]);
p&&y.push(new f({fileName:p[2],lineNumber:p[1],source:l[u]}))}return y},parseOpera10:function(l){var t=/Line (\d+).*script (?:in )?(\S+)(?:: In function (\S+))?$/i;l=l.stacktrace.split("\n");for(var y=[],u=0,q=l.length;u<q;u+=2){var p=t.exec(l[u]);p&&y.push(new f({functionName:p[3]||void 0,fileName:p[2],lineNumber:p[1],source:l[u]}))}return y},parseOpera11:function(l){return l.stack.split("\n").filter(function(t){return!!t.match(h)&&!t.match(/^Error created at/)},this).map(function(t){var y=t.split("@"),
u=this.extractLocation(y.pop()),q=y.shift()||"";y=q.replace(/<anonymous function(: (\w+))?>/,"$2").replace(/\([^)]*\)/g,"")||void 0;var p;q.match(/\(([^)]*)\)/)&&(p=q.replace(/^[^(]+\(([^)]*)\)$/,"$1"));p=void 0===p||"[arguments not available]"===p?void 0:p.split(",");return new f({functionName:y,args:p,fileName:u[0],lineNumber:u[1],columnNumber:u[2],source:t})},this)}}})})(ub);var Ad=function(a){return a&&a.__esModule&&Object.prototype.hasOwnProperty.call(a,"default")?a["default"]:a}(ub.exports),
r={htmlCollectionToArray:function(a){var d=[],f;if(!a||!a.length)return d;for(f=0;f<a.length;f++)d.push(a[f]);return d},find:function(a){if(!document.querySelectorAll||!a)return[];a=document.querySelectorAll(a);return r.htmlCollectionToArray(a)},findMultiple:function(a){if(!a||!a.length)return[];var d,f=[];for(d=0;d<a.length;d++){var h=r.find(a[d]);f=f.concat(h)}return f=r.makeNodesUnique(f)},findNodesByTagName:function(a,d){if(!a||!d||!a.getElementsByTagName)return[];var f=a.getElementsByTagName(d);
return r.htmlCollectionToArray(f)},makeNodesUnique:function(a){var d=[].concat(a);a.sort(function(l,t){if(l===t)return 0;var y=fa(d,l),u=fa(d,t);return y===u?0:y>u?-1:1});if(1>=a.length)return a;var f=0,h=0,k=[],n;for(n=a[f++];n;)n===a[f]&&(h=k.push(f)),n=a[f++]||null;for(;h--;)a.splice(k[h],1);return a},getAttributeValueFromNode:function(a,d){if(r.hasNodeAttribute(a,d)){if(a&&a.getAttribute)return a.getAttribute(d);if(a&&a.attributes&&"undefined"!==R(a.attributes[d])){if(a.attributes[d].value)return a.attributes[d].value;
if(a.attributes[d].nodeValue)return a.attributes[d].nodeValue;var f,h=a.attributes;if(h){for(f=0;f<h.length;f++)if(h[f].nodeName===d)return h[f].nodeValue;return null}}}},hasNodeAttributeWithValue:function(a,d){return!!r.getAttributeValueFromNode(a,d)},hasNodeAttribute:function(a,d){return a&&a.hasAttribute?a.hasAttribute(d):a&&a.attributes?"undefined"!==R(a.attributes[d]):!1},hasNodeCssClass:function(a,d){if(a&&d&&a.className){var f="string"===typeof a.className?a.className.split(" "):[];if(-1!==
fa(f,d))return!0}return!1},findNodesHavingAttribute:function(a,d,f){f||(f=[]);if(!a||!d)return f;a=hc(a);if(!a)return f;var h;for(h=0;h<a.length;h++){var k=a[h];r.hasNodeAttribute(k,d)&&f.push(k);f=r.findNodesHavingAttribute(k,d,f)}return f},findFirstNodeHavingAttribute:function(a,d){if(a&&d){if(r.hasNodeAttribute(a,d))return a;var f=r.findNodesHavingAttribute(a,d);if(f&&f.length)return f[0]}},findFirstNodeHavingAttributeWithValue:function(a,d){if(a&&d){if(r.hasNodeAttributeWithValue(a,d))return a;
var f=r.findNodesHavingAttribute(a,d);if(f&&f.length){var h;for(h=0;h<f.length;h++)if(r.getAttributeValueFromNode(f[h],d))return f[h]}}},findNodesHavingCssClass:function(a,d,f){f||(f=[]);if(!a||!d)return f;if(a.getElementsByClassName)return d=a.getElementsByClassName(d),r.htmlCollectionToArray(d);a=hc(a);if(!a)return[];var h;for(h=0;h<a.length;h++){var k=a[h];r.hasNodeCssClass(k,d)&&f.push(k);f=r.findNodesHavingCssClass(k,d,f)}return f},findFirstNodeHavingClass:function(a,d){if(a&&d){if(r.hasNodeCssClass(a,
d))return a;var f=r.findNodesHavingCssClass(a,d);if(f&&f.length)return f[0]}},isLinkElement:function(a){if(!a)return!1;a=String(a.nodeName).toLowerCase();return-1!==fa(["a","area"],a)},setAnyAttribute:function(a,d,f){a&&d&&(a.setAttribute?a.setAttribute(d,f):a[d]=f)}},kd=/^[a-z]+:\/\/.+$/i,kc=[15,30,60,120,240,480,960,1800],wa={PeriodicHeartbeat:1,LastHeartbeat:2,BlurHeartbeat:3,Deanonymize:4,PerformanceMetrics:5,OnDemand:6},Ua,za={},ea={},B=document,U=navigator,gd=screen,A=window,Gc=!1,F=A.encodeURIComponent,
qc=A.decodeURIComponent,Q=[],ec=[],Ha,db=[],E={CONTENT_ATTR:"data-track-content",CONTENT_CLASS:"piwikTrackContent",CONTENT_NAME_ATTR:"data-content-name",CONTENT_PIECE_ATTR:"data-content-piece",CONTENT_PIECE_CLASS:"piwikContentPiece",CONTENT_TARGET_ATTR:"data-content-target",CONTENT_TARGET_CLASS:"piwikContentTarget",CONTENT_IGNOREINTERACTION_ATTR:"data-content-ignoreinteraction",CONTENT_IGNOREINTERACTION_CLASS:"piwikContentIgnoreInteraction",CONTENT_WATCHED_ATTR:"data-content-watched",location:void 0,
findContentNodes:function(){return r.findMultiple(["."+this.CONTENT_CLASS,"["+this.CONTENT_ATTR+"]"])},findContentNodesWithinNode:function(a){if(!a)return[];var d=r.findNodesHavingCssClass(a,this.CONTENT_CLASS),f=r.findNodesHavingAttribute(a,this.CONTENT_ATTR);if(f&&f.length){var h;for(h=0;h<f.length;h++)d.push(f[h])}r.hasNodeAttribute(a,this.CONTENT_ATTR)?d.push(a):r.hasNodeCssClass(a,this.CONTENT_CLASS)&&d.push(a);return d=r.makeNodesUnique(d)},findParentContentNode:function(a){if(a)for(var d=0;a&&
a!==B&&a.parentNode;){if(r.hasNodeAttribute(a,this.CONTENT_ATTR)||r.hasNodeCssClass(a,this.CONTENT_CLASS))return a;a=a.parentNode;if(1E3<d)break;d++}},findPieceNode:function(a){var d;(d=r.findFirstNodeHavingAttribute(a,this.CONTENT_PIECE_ATTR))||(d=r.findFirstNodeHavingClass(a,this.CONTENT_PIECE_CLASS));return d?d:a},findTargetNodeNoDefault:function(a){if(a){var d=r.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_TARGET_ATTR);if(d||(d=r.findFirstNodeHavingAttribute(a,this.CONTENT_TARGET_ATTR))||
(d=r.findFirstNodeHavingClass(a,this.CONTENT_TARGET_CLASS)))return d}},findTargetNode:function(a){var d=this.findTargetNodeNoDefault(a);return d?d:a},findTargetNodesNoDefault:function(a){if(a){var d=r.findNodesHavingAttribute(a,this.CONTENT_TARGET_ATTR);if(d&&0<d.length||(d=r.findNodesHavingCssClass(a,this.CONTENT_TARGET_CLASS))&&0<d.length)return d}},findTargetNodes:function(a){var d=E.findTargetNodesNoDefault(a);return d&&0<d.length?d:[a]},findContentName:function(a){if(a){var d=r.findFirstNodeHavingAttributeWithValue(a,
this.CONTENT_NAME_ATTR);if(d)return r.getAttributeValueFromNode(d,this.CONTENT_NAME_ATTR);if(d=this.findContentPiece(a))return this.removeDomainIfIsInLink(d);if(r.hasNodeAttributeWithValue(a,"title"))return r.getAttributeValueFromNode(a,"title");d=this.findPieceNode(a);if(r.hasNodeAttributeWithValue(d,"title"))return r.getAttributeValueFromNode(d,"title");a=this.findTargetNode(a);if(r.hasNodeAttributeWithValue(a,"title"))return r.getAttributeValueFromNode(a,"title")}},findContentPiece:function(a){if(a){var d=
r.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_PIECE_ATTR);if(d)return r.getAttributeValueFromNode(d,this.CONTENT_PIECE_ATTR);a=this.findPieceNode(a);if(a=this.findMediaUrlInNode(a))return this.toAbsoluteUrl(a)}},findContentTarget:function(a){if(a){var d=this.findTargetNode(a);if(r.hasNodeAttributeWithValue(d,this.CONTENT_TARGET_ATTR))return r.getAttributeValueFromNode(d,this.CONTENT_TARGET_ATTR);if(r.hasNodeAttributeWithValue(d,"href"))return a=r.getAttributeValueFromNode(d,"href"),this.toAbsoluteUrl(a);
a=this.findPieceNode(a);if(r.hasNodeAttributeWithValue(a,"href"))return a=r.getAttributeValueFromNode(a,"href"),this.toAbsoluteUrl(a)}},isSameDomain:function(a){if(!a||!a.indexOf)return!1;if(0===a.indexOf(this.getLocation().origin))return!0;a=a.indexOf(this.getLocation().host);return 8>=a&&0<=a?!0:!1},removeDomainIfIsInLink:function(a){a&&a.search&&-1!==a.search(/^https?:\/\/[^/]+/)&&this.isSameDomain(a)&&((a=a.replace(/^.*\/\/[^/]+/,""))||(a="/"));return a},findMediaUrlInNode:function(a){if(a){var d=
a.nodeName.toLowerCase();if(-1!==fa(["img","embed","video","audio"],d)&&r.findFirstNodeHavingAttributeWithValue(a,"src"))return a=r.findFirstNodeHavingAttributeWithValue(a,"src"),r.getAttributeValueFromNode(a,"src");if("object"===d&&r.hasNodeAttributeWithValue(a,"data"))return r.getAttributeValueFromNode(a,"data");if("object"===d){if((d=r.findNodesByTagName(a,"param"))&&d.length){var f;for(f=0;f<d.length;f++)if("movie"===r.getAttributeValueFromNode(d[f],"name")&&r.hasNodeAttributeWithValue(d[f],"value"))return r.getAttributeValueFromNode(d[f],
"value")}if((a=r.findNodesByTagName(a,"embed"))&&a.length)return this.findMediaUrlInNode(a[0])}}},trim:function(a){return Z(a)},isOrWasNodeInViewport:function(a){if(!a||!a.getBoundingClientRect||1!==a.nodeType)return!0;var d=a.getBoundingClientRect(),f=B.documentElement||{},h=0>d.top;h&&a.offsetTop&&(h=0<a.offsetTop+d.height);a=f.clientWidth;A.innerWidth&&a>A.innerWidth&&(a=A.innerWidth);f=f.clientHeight;A.innerHeight&&f>A.innerHeight&&(f=A.innerHeight);return(0<d.bottom||h)&&0<d.right&&d.left<a&&
(d.top<f||h)},isNodeVisible:function(a){var d=Ab(a);a=this.isOrWasNodeInViewport(a);return d&&a},buildInteractionRequestParams:function(a,d,f,h){var k="";a&&(k+="c_i="+F(a));d&&(k&&(k+="&"),k+="c_n="+F(d));f&&(k&&(k+="&"),k+="c_p="+F(f));h&&(k&&(k+="&"),k+="c_t="+F(h));return k},buildImpressionRequestParams:function(a,d,f){a="c_n="+F(a)+"&c_p="+F(d);f&&(a+="&c_t="+F(f));return a},buildContentBlock:function(a){if(a){var d=this.findContentName(a),f=this.findContentPiece(a);a=this.findContentTarget(a);
d=this.trim(d);f=this.trim(f);a=this.trim(a);return{name:d||"Unknown",piece:f||"Unknown",target:a||""}}},collectContent:function(a){if(!a||!a.length)return[];var d=[],f;for(f=0;f<a.length;f++){var h=this.buildContentBlock(a[f]);v(h)&&d.push(h)}return d},setLocation:function(a){this.location=a},getLocation:function(){var a=this.location||A.location;a.origin||(a.origin=a.protocol+"//"+a.hostname+(a.port?":"+a.port:""));return a},toAbsoluteUrl:function(a){return a&&String(a)===a||""===a?""===a?this.getLocation().href:
-1!==a.search(/^\/\//)?this.getLocation().protocol+a:-1!==a.search(/:\/\//)?a:0===a.indexOf("#")||0===a.indexOf("?")?this.getLocation().origin+this.getLocation().pathname+a:0===a.search("^[a-zA-Z]{2,11}:")?a:-1!==a.search(/^\//)?this.getLocation().origin+a:this.getLocation().origin+this.getLocation().pathname.match(/(.*\/)/)[0]+a:a},isUrlToCurrentDomain:function(a){a=this.toAbsoluteUrl(a);if(!a)return!1;var d=this.getLocation().origin;return d===a?!0:0===String(a).indexOf(d)?":"===String(a).substr(d.length,
1)?!1:!0:!1},setHrefAttribute:function(a,d){a&&d&&r.setAnyAttribute(a,"href",d)},shouldIgnoreInteraction:function(a){var d=r.hasNodeAttribute(a,this.CONTENT_IGNOREINTERACTION_ATTR);a=r.hasNodeCssClass(a,this.CONTENT_IGNOREINTERACTION_CLASS);return d||a}},Dd="addTracker disableCookies enableCookies setSessionIdStrictPrivacyMode setTrackerUrl setAPIUrl enableCrossDomainLinking setCrossDomainLinkingTimeout customCrossDomainLinkDecorator customCrossDomainLinkVisitorIdGetter setSecureCookie setCookiePath setCookieDomain setDomains setUserId setSiteInspectorSetup setSiteId enableLinkTracking setCustomVariableMaximumLength setDeviceDataAnonymization setEnableClientHints".split(" ");
X(A,"beforeunload",function(){var a;for(a=0;a<Q.length;a+=1)Q[a].trackHeartBeat({lastHeartbeat:!0});for(a=0;a<ec.length;a+=1)ec[a].trackHeartBeat({lastHeartbeat:!0});zb("unload");if(Ua){do a=new Date;while(a.getTimeAlias()<Ua)}},!1);Date.prototype.getTimeAlias=Date.prototype.getTime;var ya={initialized:!1,JSON:JSON,DOM:{addEventListener:function(a,d,f,h){"undefined"===R(h)&&(h=!1);X(a,d,f,h)},onLoad:Ga,onReady:Sa,isNodeVisible:Ab,isOrWasNodeVisible:E.isNodeVisible},on:function(a,d){ea[a]||(ea[a]=
[]);ea[a].push(d)},off:function(a,d){if(ea[a]){var f=0;for(f;f<ea[a].length;f++)ea[a][f]===d&&ea[a].splice(f,1)}},trigger:function(a,d,f){if(ea[a]){var h=0;for(h;h<ea[a].length;h++)ea[a][h].apply(f||A,d)}},addPlugin:function(a,d){za[a]=d},getTracker:function(a,d){v(d)||(d=this.getAsyncTracker().getSiteId());v(a)||(a=this.getAsyncTracker().getTrackerUrl());var f=new Bb(a,d);ec.push(f);return f},getAsyncTrackers:function(){return Q},addTracker:function(a,d){return Q.length?Q[0].addTracker(a,d):hd(a,
d)},getAsyncTracker:function(a,d){if(Q&&Q.length&&Q[0])var f=Q[0];else return hd(a,d);if(!d&&!a)return f;v(d)&&null!==d||!f||(d=f.getSiteId());v(a)&&null!==a||!f||(a=f.getTrackerUrl());var h=0;for(h;h<Q.length;h++)if((f=Q[h])&&String(f.getSiteId())===String(d)&&f.getTrackerUrl()===a)return f},retryMissedPluginCalls:function(){var a=db;db=[];var d=0;for(d;d<a.length;d++)Ra(a[d])}};"function"===typeof define&&define.amd&&define("piwik",[],function(){return ya});ub=ya;"object"!==R(window._paq)&&(window._paq=
[]);"object"!==R(window.Piwik)&&(window.Piwik=ub);(function(){if(window&&"object"===R(window.piwikPluginAsyncInit)&&window.piwikPluginAsyncInit.length){var a=0;for(a;a<window.piwikPluginAsyncInit.length;a++)if("function"===typeof window.piwikPluginAsyncInit[a])window.piwikPluginAsyncInit[a]()}window&&window.piwikAsyncInit&&window.piwikAsyncInit();window.Piwik.getAsyncTrackers().length?M("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/."):
("object"!==R(window._paq)||"undefined"===R(window._paq.length)?0:window._paq.length)?window.Piwik.addTracker():window._paq={push:function(d){M("_paq.push() was used but Piwik tracker was not initialized before the ppms.js file was loaded. Make sure to configure the tracker via _paq.push before loading ppms.js. Alternatively, you can create a tracker via Piwik.addTracker() manually and then use _paq.push but it may not fully work as tracker methods may not be executed in the correct order.")}};window.Piwik.trigger("PiwikInitialized",
[]);window.Piwik.initialized=!0})();"undefined"===R(window.AnalyticsTracker)&&(window.AnalyticsTracker=window.Piwik);"function"!==typeof window.piwik_log&&(window.piwik_log=Ed)})()
//# sourceMappingURL=ppms.js.map
