#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 21 18:08:29 2021

@author: Theo
"""
pck_kwargs={
    'dis': dict(length_units=None,
                    nogrb=None,
                    xorigin=None,
                    yorigin=None,
                    angrot=None,
                    nlay=1,
                    nrow=2,
                    ncol=2,
                    delr=1.0,
                    delc=1.0,
                    top=1.0,
                    botm=0.0,
                    idomain=None,
                    filename=None,
                    pname=None,
                    parent_file=None,
                    ),
    'npf': dict(save_flows=None,
                    alternative_cell_averaging=None,
                    thickstrt=None,
                    cvoptions=None,
                    perched=None,
                    rewet_record=None,
                    xt3doptions=None,
                    save_specific_discharge=None,
                    save_saturation=None,
                    k22overk=None,
                    k33overk=None,
                    icelltype=0,
                    k=1.0,
                    k22=None,
                    k33=None,
                    angle1=None,
                    angle2=None,
                    angle3=None,
                    wetdry=None,
                    filename=None,
                    pname=None,
                    parent_file=None,
                    ),
    'chd': dict(auxiliary=None,
                    auxmultname=None,
                    boundnames=None,
                    print_input=None,
                    print_flows=None,
                    save_flows=None,
                    timeseries=None,
                    observations=None,
                    maxbound=None,
                    stress_period_data=None,
                    filename=None,
                    pname=None,
                    parent_file=None,
                    ),
    'ghb': dict(auxiliary=None,
                  auxmultname=None,
                  boundnames=None,
                  print_input=None,
                  print_flows=None,
                  save_flows=None,
                  timeseries=None,
                  observations=None,
                  mover=None, maxbound=None,
                  stress_period_data=None,
                  filename=None,
                  pname=None,
                  parent_file=None,
                  ),
    'riv': dict(auxiliary=None,
                    auxmultname=None,
                    boundnames=None,
                    print_input=None,
                    print_flows=None,
                    save_flows=None,
                    timeseries=None,
                    observations=None,
                    mover=None,
                    maxbound=None,
                    stress_period_data=None,
                    filename=None,
                    pname=None,
                    parent_file=None,
                    ),
    'drn': dict(auxiliary=None,
                    auxmultname=None,
                    auxdepthname=None,
                    boundnames=None,
                    print_input=None,
                    print_flows=None,
                    save_flows=None,
                    timeseries=None,
                    observations=None,
                    mover=None,
                    maxbound=None,
                    stress_period_data=None,
                    filename=None,
                    pname=None,
                    parent_file=None,
                    ),
    'wel': dict(auxiliary=None,
                    auxmultname=None,
                    boundnames=None,
                    print_input=None,
                    print_flows=None,
                    save_flows=None,
                    auto_flow_reduce=None,
                    timeseries=None,
                    observations=None,
                    mover=None,
                    maxbound=None,
                    stress_period_data=None,
                    filename=None,
                    pname=None,
                    parent_file=None,
                    ),
    }