# File generated by Flopy version 3.3.3 on 05/23/2021 at 20:08:28.
BEGIN attributes
  NAMES  Qwell
  METHODS  stepwise
  SFACS       1.00000000
END attributes

BEGIN timeseries
       0.00000000    -600.00000000
       5.00000000    -200.00000000
       7.00000000    -400.00000000
       9.00000000    -300.00000000
      10.00000000       0.00000000
     100.00000000       0.00000000
END timeseries

